blank_issues_enabled: false
contact_links:
  - name: Request a feature
    url: https://github.com/ostark/craft-relax/issues/new
    about: Share ideas for new features
    title: "[Idea]"
    labels: enhancement
  - name: Report a bug
    url: https://github.com/ostark/craft-relax/issues/new
    about: Report a reproducable bug
    title: "[Bug]"
    labels: bug
